books/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),

    path('authors/', views.authors, name='authors'),
    path('authors/<int:pk>/', views.authors_detail, name='authors_detail'),

    path('publishers/', views.publishers, name='publishers'),
    path('stores/', views.stores, name='stores'),

    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/update/<int:pk>/', views.BookUpdate.as_view(), name='book-update'),
    path('book/delete/<int:pk>/', views.BookDelete.as_view(), name='book-delete'),
    path('books/<int:pk>/', views.BookDetail.as_view(), name='books_detail'),
    path('books/', views.BookList.as_view(), name='books'),
]

hw_11/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('books.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

books/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    def __str__(self):
        return self.name, self.age


class Publisher(models.Model):
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=300)
    pages = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    rating = models.FloatField()
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    pubdate = models.DateField()

    def __str__(self):
        return self.name

    def display_authors(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([genre.name for genre in self.authors.all()[:3]])
    display_authors.short_description = 'Authors'


class Store(models.Model):
    name = models.CharField(max_length=300)
    books = models.ManyToManyField(Book)

    def __str__(self):
        return self.name, self.books

    def display_books(self):
        """
        Creates a string for the Books. This is required to display Books in Admin.
        """
        return ', '.join([genre.name for genre in self.books.all()[:3]])
    display_books.short_description = 'Books'

books/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Avg, Count
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView

from .models import Author, Book, Publisher, Store


@cache_page(10)
def authors(request):
    author = Author.objects.prefetch_related('book_set__authors')
    average_rating = Author.objects.aggregate(avg_rating=Avg('book__rating'))
    context = {'authors': author, 'average_rating': average_rating['avg_rating']}
    return render(request, 'books_temp/authors_list.html', context)


@cache_page(10)
def publishers(request):
    publishers = Publisher.objects.all().annotate(num_books=Count('book'))
    return render(request, 'books_temp/publishers.html', {'publishers': publishers})


@cache_page(10)
def stores(request):
    stores = Store.objects.all().annotate(num_books=Count('books'))
    return render(request, 'books_temp/stores.html', {'stores': stores})


@cache_page(10)
def authors_detail(request, pk):
    author = get_object_or_404(Author, pk=pk)
    books = Book.objects.select_related('publisher')
    return render(request, 'books_temp/authors_inf.html', {'author': author, 'books': books})


class HomePageView(TemplateView):
    template_name = 'books_temp/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_books'] = Book.objects.count()
        context['num_authors'] = Author.objects.count()
        context['num_publishers'] = Publisher.objects.count()
        context['num_stores'] = Store.objects.count()
        return context


class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    template_name = 'books_temp/new_book.html'
    fields = ['name', 'pages', 'price', 'rating', 'authors', 'publisher', 'pubdate']
    success_url = reverse_lazy('books')
    login_url = '/admin/login/'


class BookUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Book
    template_name = 'books_temp/book_update.html'
    fields = ['name', 'pages', 'price', 'rating', 'authors', 'publisher', 'pubdate']
    success_message = "Book updated!"
    login_url = '/admin/login/'
    redirect_field_name = 'admin'

    def get_success_url(self):
        book_id = self.kwargs['pk']
        return reverse_lazy('book-update', kwargs={'pk': book_id})


class BookDelete(LoginRequiredMixin, DeleteView):
    model = Book
    template_name = 'books_temp/book_delete.html'
    success_url = reverse_lazy('books')
    login_url = '/admin/login/'


@method_decorator(cache_page(10), name='dispatch')
class BookDetail(DetailView):
    model = Book
    template_name = 'books_temp/books_inf.html'


@method_decorator(cache_page(10), name='dispatch')
class BookList(ListView):
    model = Book
    template_name = 'books_temp/books_list.html'
    paginate_by = 700
    queryset = Book.objects.annotate(num_authors=Count('authors')).select_related('publisher')
    context_object_name = 'books'

templates/books_temp/authors_inf.html
{% extends 'main.html' %}

{% block title %}Author information{% endblock %}

{% block content %}
    <div>
        <p><a href="{% url 'authors' %}">Go back to the list of authors</a></p>
        <h1>Author: {{ author.name }}, age: {{ author.age }} </h1>
        <p>Number of his books: {{ author.book_set.count }}</p>
        <table>
            <caption>List of books:</caption>
            <tr>
                <th>Name</th>
                <th>Pages</th>
                <th>Price</th>
                <th>Rating</th>
                <th>Publisher</th>
                <th>Publication date</th>
            </tr>
            {% for book in books %}
                <tr>
                <td><a href="{% url 'books_detail' pk=book.id %}"> {{ book.name }}</a></td>
                <td>{{ book.pages }}</td>
                <td>{{ book.price }}</td>
                <td>{{ book.rating }}</td>
                <td>{{ book.publisher }}</td>
                <td>{{ book.pubdate }}</td>
                </tr>
            {% endfor %}
        </table>
    <p><a href="{% url 'index' %}">Go to main page</a></p>
    </div>
{% endblock %}

templates/books_temp/authors_list.html
{% extends 'main.html' %}

{% block title %}List of authors{% endblock %}

{% block content %}
    <p><a href="{% url 'index' %}">Return to home page</a></p>
        <div>
            <p>Average rating of all the books we have written by authors: {{ avg_rating }}</p>
            <h1>List of authors:</h1>
        </div>
        <table>
            <caption><h2>Authors</h2></caption>
            <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Books</th>
            </tr>
            {% for author in authors %}
                    <td><a href="{% url 'authors_detail' pk=author.pk %}">{{ author.name }}</a></td>
                    <td>{{ author.age }}</td>
                    <td>{{ author.book_set.all|length }} </td>
                </tr>
            {% endfor %}
        </table>
{% endblock %}

templates/books_temp/book_delete.html
{% extends 'main.html' %}

{% block title %}Book delete{% endblock %}

{% block content %}
    <h1>Delete Book</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Delete book">
        <p><a href="{% url 'index' %}">Go to main page</a></p>
    </form>
{% endblock %}

templates/books_temp/book_update.html
{% extends 'main.html' %}

{% block title %}Update book{% endblock %}

{% block content %}
    <h1>Update Book</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Update book">
        <p><a href="{% url 'index' %}">Go to main page</a></p>
    </form>
{% endblock %}

templates/books_temp/books_inf.html
{% extends 'main.html' %}

{% block title %}Selected book<{% endblock %}

{% block content %}
    <p><a href="{% url 'books' %}">Go back to the list of books</a></p>
    <h1>Book: {{ book.name }}</h1>
    <table>
        <caption>{{ book.name }}</caption>
        <tr>
            <th>Pages</th>
            <th>Price</th>
            <th>Rating</th>
            <th>Author</th>
            <th>Publisher</th>
            <th>Publication date</th>
            <th>Store</th>
        </tr>
        <tr>
            <td>{{ book.pages }}</td>
            <td>{{ book.price }}</td>
            <td>{{ book.rating }}</td>
            <td>
                {% for author in book.authors.all %}
                    <a href="{% url 'authors_detail' pk=author.pk %}">{{ author.name }}
                {% endfor %}
            </td>
            <td>{{ book.publisher }}</td>
            <td>{{ book.pubdate }}</td>
            <td>
                {% for store in book.store_set.all %}
                   {{ store.name }};
                {% endfor %}
            </td>
        </tr>
    </table>
    <button type="button"><a href="../../book/update/{{ book.id }}">Update</a></button>
    <button type="button"><a href="{% url 'book-create' %}">Create new book</a></button>
    <button type="button"><a href="../../book/delete/{{ book.id }}">Delete</a></button>
{% endblock %}

templates/books_temp/books_list.html
{% extends 'main.html' %}

{% block title %}List of books{% endblock %}

{% block content %}
    <p><a href="{% url 'index' %}">Go to main page</a></p>
    <p><a href="{% url 'book-create' %}"> Create Book</a></p>
        <div>
            <h1>List of books:</h1>
        </div>
        <table>
            <caption><h2>Books</h2></caption>
            <tr>
                <th>Name</th>
                <th>Pages</th>
                <th>Price</th>
                <th>Rating</th>
                <th>Publisher</th>
                <th>Publication date</th>
                <th>Number of authors</th>
            </tr>
            {% for author in authors %}
                    <td><a href="{% url 'books_detail' pk=book.pk %}"> {{ book.name }}</a></td>
                    <td>{{ book.pages }}</td>
                    <td>{{ book.price }}</td>
                    <td>{{ book.rating }}</td>
                    <td>{{ book.publisher }}</td>
                    <td>{{ book.pubdate }}</td>
                    <td>{{ book.num_authors }}</td>
                </tr>
            {% endfor %}
        </table>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/books_temp/home.html
{% extends "main.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>You are on the home page!</h1>
    <p><a href="{% url 'books_list' %}">Books list</a></p>
{% endblock %}

templates/books_temp/index.html
{% extends 'main.html' %}

{% block title %}Library{% endblock %}

{% block content %}
    <h1>You are on the home page!</h1>
    <ul>
        <li>Books: <a href="{% url 'books' %}">{{ num_books }}</a></li>
        <li>Authors: <a href="{% url 'authors' %}">{{ num_authors }}</a></li>
        <li>Publishers: <a href="{% url 'publishers' %}">{{ num_publishers }}</a></li>
        <li>Stores: <a href="{% url 'stores' %}">{{ num_stores }}</a></li>
    </ul>
{% endblock %}

templates/books_temp/new_book.html
{% extends 'main.html' %}

{% block title %}Create new book{% endblock %}

{% block content %}
    <h1>New Book</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Create book">
        <p><a href="{% url 'index' %}">Go to main page</a></p>
    </form>
{% endblock %}

templates/books_temp/publishers.html
{% extends 'main.html' %}

{% block title %}List of publishers{% endblock %}

{% block content %}
    <p><a href="{% url 'index' %}">Go back to the home page</a></p>
    {% if publishers %}
        <div>
            <h1>List of publishers:</h1>
        </div>
        <table>
        <caption>List of publishers:</caption>
        <tr>
            <th>Name</th>
            <th>Count of books</th>
        </tr>
        {% for publisher in publishers %}
            <tr>
                <td>{{ publisher.name }}</td>
                <td>{{ publisher.num_books }}</td>
            </tr>
        {% endfor %}
        </table>
    {% endif %}
{% endblock %}

templates/books_temp/stores.html
{% extends 'main.html' %}

{% block title %}List of stores{% endblock %}

{% block content %}
    <p><a href="{% url 'index' %}">Go back to the home page</a></p>
    {% if stores %}
        <h1>List of stores:</h1>
        <table>
            <caption>List of stores:</caption>
            <tr>
                <th>Name</th>
                <th>Count of books</th>
            </tr>
            {% for store in stores %}
                <tr>
                    <td>{{ store.name }}</td>
                    <td>{{ store.num_books }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>